import os
import pandas as pd
import sys
from io import StringIO


# ==========================================
# AGENT 1 TOOLS: Data Cleaner
# ==========================================

def inspect_metadata(df):
    """Returns shape, data types, and null counts."""
    buffer = StringIO()
    df.info(buf=buffer)
    return buffer.getvalue()


def get_column_stats(df, col):
    """Returns basic distribution statistics or unique values."""
    if col not in df.columns:
        return f"Error: Column '{col}' not found."
    return str(df[col].describe(include='all').to_dict())


def impute_missing(df, col, strategy='median'):
    """Fills NaNs inside a column based on mean, median, or mode."""
    if col not in df.columns:
        return df
    if strategy == 'median':
        df[col] = df[col].fillna(df[col].median())
    elif strategy == 'mean':
        df[col] = df[col].fillna(df[col].mean())
    elif strategy == 'mode':
        df[col] = df[col].fillna(df[col].mode()[0])
    return df


def drop_column(df, col):
    """Removes an unusable column from the dataframe."""
    if col in df.columns:
        df = df.drop(columns=[col])
    return df


# ==========================================
# AGENT 2 TOOLS: Feature Engineer
# ==========================================

def create_interaction(df, expression):
    """Evaluates a mathematical string to generate a new column safely."""
    try:
        # Example expression: "income / age" -> evaluated inside dataframe context
        col_name = expression.replace(" ", "_").replace("/", "_per_").replace("*", "_times_")
        df[col_name] = df.eval(expression)
        return df, f"Successfully created feature: {col_name}"
    except Exception as e:
        return df, f"Error creating feature: {e}"


def encode_categorical(df, col):
    """Applies one-hot encoding to a categorical column."""
    if col in df.columns:
        df = pd.get_dummies(df, columns=[col], drop_first=True)
    return df


def correlation_analysis(df, target):
    """Checks linear correlation coefficients against the label."""
    if target not in df.columns:
        return "Target column not found."
    corr = df.select_dtypes(include=['number']).corr()[target].sort_values(ascending=False)
    return corr.to_string()


# ==========================================
# AGENT 3 TOOLS: Model Trainer Execution
# ==========================================

def execute_python_code(code_string):
    """Runs Python code generated by the LLM dynamically and captures console metrics."""
    old_stdout = sys.stdout
    redirected_output = sys.stdout = StringIO()

    try:
        # Execute the code string in a local context environment
        exec(code_string, globals())
        sys.stdout = old_stdout
        return redirected_output.getvalue(), None
    except Exception as e:
        sys.stdout = old_stdout
        return "", str(e)